import React from "react";
import Head from "next/head";
import { Roboto } from "next/font/google";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
export const metadata = {
  title: "Acme",
  description: "Generated by create next app",
  openGraph: {
    title: "Acme",
    description: "Acme is a...",
  },
};
const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <div className={`${roboto.className} layout`}>{children}</div>
    </>
  );
};

export default Layout;
